mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView
from pol import views
urlpatterns = [
    path('',include('pol.urls')),
    path('admin/', admin.site.urls),
 
    
]

mysite/pol/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'pol'

urlpatterns = [
    # ex: /polls/
    path('', views.index_view, name='mhome'),
    path('upload/', views.upload, name='upload'),
    path('books/', views.book_list, name='book_list'),
    path('books/upload/', views.Upload_book, name='upload_book'),
    path('main/', views.home_view, name='home'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('register/', views.register_view, name='register_url'),
    path('login/', LoginView.as_view(), name="login_urls" ),
    path('logout/', LogoutView.as_view(next_page='pol:mhome'),name="logout_url"),
    path('resources/', views.Resource_View, name='resource'),
    path('profile/', views.Profile_View, name='profile'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/pol/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
# Create your models her
class profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpeg',upload_to='profile_pic')
    pdf = models.FileField(default='user.pdf',upload_to='props/pdfs')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    pdf = models.FileField(upload_to='books/pdfs')

    def __str__(self):
        return self.title


class Proposal(models.Model):
    title = models.CharField(max_length=100)
    pdf = models.FileField(upload_to="proposals/pdfs")

    def __str__(self):
        return self.title

mysite/pol/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Book,Proposal,profile

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'pdf')

class ProposalForm(forms.ModelForm):
    class Meta:
        model = profile
        fields = ['pdf']



class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = profile
        fields = ['image']

mysite/pol/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from .forms import BookForm,ProposalForm, UserUpdateForm, ProfileUpdateForm
from .models import Book
from .models import Proposal,profile
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import confusion_matrix
import nltk
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
from sklearn.cluster import KMeans
import pandas as pd
import pickle
import numpy as np
import string
import re
from . import categorize
import collections
import random
from . import kmeans


# Create your views here.

def upload(request):
    context={}
    if request.method == 'POST':
        uploaded_file = request.FILES['document']
        print(uploaded_file.name)
        print(uploaded_file.size)
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name,uploaded_file)
        context['url'] = fs.url(name)
    
    return render(request, 'pol/upload.html',context)

def book_list(request):
    books = Book.objects.all()
    return render(request,'pol/book_list.html',{
        'books':books
    })

def Upload_book(request):
    form = ProposalForm()
    if request.method == 'POST':
        form = ProposalForm(request.POST,
                                request.FILES,
                                instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('pol:dashboard')
        else:
            form = ProposalForm(instance=request.user.profile)

    return render(request,'pol/Upload_book.html',{'form':form})



def index_view(request):
    return render(request,'pol/index.html')
    
def home_view(request):
    #takes value from search
    text=request.POST.get('searches')
    
    disp_text=text
    k={}
    [k,w]=categorize.categorize_idf(disp_text)
    wt=w
    if disp_text!=None:
        kt=kmeans.kmean_categorize(disp_text)
        kcont = {
            'km':kt,
        }
    else:
        kcont = {
            'km':"  "
        }
    
    categ_str = {
        'h':'',
        'string':disp_text,
    }
    z = kmeans.kmean_categorize(wt)
    cont = {
        'm':z,
    }    
    #print(z)
    return render(request, 'pol/base.html', {'k': k,'cont' : cont, 
    'categ_str' : categ_str, 'kcont' : kcont})

def Resource_View(request):
    return render(request,'pol/resources.html')


@login_required

def Profile_View(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('pol:profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request,'pol/profile.html',context)

def dashboard_view(request):       #for dashboard
    prop = ProposalForm(instance=request.user.profile)
    return render(request,'pol/dashboard.html',{'prop':prop})

def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('pol:login_urls')
    else:
        form = UserCreationForm()
    return render(request,'registration/register.html',{'form':form})

mysite/templates/pol/base.html
<!DOCTYPE html>

{% load static %}

<html>
  <link rel="stylesheet" type="text/css" href="{% static 'pol/style.css' %}">
  <link rel="stylesheet" type="text/javascript" href="{% static 'pol/materialize.min.js' %}">

<head>
    <div class="s6">
    <ul id="slide-out" class="sidenav">
          
      <li><div class="user-view ">
            
        <div class="background">
             
          </div>
          <div class="right">

          </div>

        </div>
      </li>
        {% if user.is_authenticated %}
        <li><a class="btn waves-effect  waves-light " href="{% url 'pol:resource'  %}"><i class="material-icons right">send</i>Resources</a></li>
        <li><a class="btn waves-effect  waves-light " href="{% url 'pol:logout_url'  %}"><i class="material-icons right">send</i>logout</a></li>
        <li><a class="btn waves-effect  waves-light " href="{% url 'pol:dashboard'  %}"><i class="material-icons right">send</i>dashboard</a></li>
  
        {% else %}
        <li><a class="btn waves-effect  waves-light " href="{% url 'pol:resource'  %}"><i class="material-icons right">send</i>Resources</a></li>
        <li><a class="btn waves-effect  waves-light " href="{% url 'pol:mhome'  %}"><i class="material-icons right">send</i>login</a></li>
            
        {% endif %}    
        <li><div class="divider"></div></li>
    </ul>
    
    <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
              
    <script>
      document.addEventListener('DOMContentLoaded', function() {
      var elems = document.querySelectorAll('.sidenav');
          
      var instances = M.Sidenav.init(elems); 
      console.log(instances)
      });

    </script>
    <title>Internship Project</title>

      <meta charset="UTF-8">
      <meta charset="UTF-8"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <link rel="stylesheet" href="{% static 'pol/style.css' %}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </div>
</head>
  
<body  id="backcolor">
    <div class="container">            
        <div class="center">                 
          <h2> WELCOME </h2>                   
          <h3>Let's Test our Awesome Model</h3>
            
        </div>
        <div class="container row">
          <form  method="POST">            
          {% csrf_token %}            
          <div class="input-field col s8">                 
            <input  type="text" name="searches" >                
            <label for="last_name">Put your text here</label>            
          </div>
          <button class="z-depth-3 btn waves-effect waves-light " type="submit" name="action">Submit
          <i class="material-icons right">send</i>
          </button>
       </div>
 

{% if k == 1 %}
<div class="loader">
  <div class="progress">
  <div class="indeterminate"></div>
</div>
</div >  
<p class="center">please enter any text</p>

<script>
 $(window).on("load",function(){
   $(".loader").fadeout("slow")
 })
</script>
{% else %}
<div class="container">   
  <div class="  column">
    <div  class=" hoverable col s3 m6">
      <div id="transp" class="opacity z-depth-4 card blue-grey darken-1">
        <div class=" card-content white-text">
          <span class="card-title">Text</span>
          <p>
            {% for key, value in categ_str.items %} 
            <p class=""> {{value}}</p>
            {% endfor %}
          </p>
        </div>
        <div class="card-action">
  
        </div>
      </div>
    </div>
  </div>
            
  <div class="column">
    <div class="hoverable col s3 m6">
      <div class="z-depth-4 card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Extracted Words</span>
          <p>
            <ul>
                {% for i in k %}
                    <li>{{ i }}</li>
                {% endfor %}
            </ul>
          </p>
        </div>
        <div class="card-action">
  
        </div>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="hoverable col s3 m6">
      <div class="z-depth-4 card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Category by TF IDF + KMEANS</span>
          <p>
            <ul>
                
                    <li>
                        {% for key, value in cont.items %} 
                        <p> {{value}}</p>
                        {% endfor %}
                        
                    </li>
                
            </ul>
          </p>
        </div>
        <div class="card-action">
  
        </div>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="hoverable col s3 m6">
      <div class="z-depth-4 card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Category by KMEANS</span>
          <p>
            <ul>
                
                    <li>
                        {% for key, value in kcont.items %} 
                        <p> {{value}}</p>
                        {% endfor %}
                        
                    </li>
                
            </ul>
          </p>
        </div>
        <div class="card-action">
  
        </div>
      </div>
    </div>
  </div>
  </div>        
    

{% endif %}




</div> 
 

  <link   href="{% static 'pol/display.js' %}">

    </body>

</html>

mysite/templates/pol/book_list.html
{% extends 'pol/index.html' %}

{% block content %}
<h1>books</h1>
{% for book in books %}
<P>
    {{ book.title}}</P>
 
<p>
    {{ book.pdf}}
</p>   

{% endfor %}
{% endblock %}

mysite/templates/pol/dashboard.html
{% extends 'pol/index.html' %}
{% load static %}
{% block content %}


<div class="container">

<h2 class="center">Welcome {{ user.username }} to dashboard</h2>
<div class="row center">
<a class="btn" href="{% url 'pol:upload_book' %}">For uploading pdf</a>
<a class="btn" href="{% url 'pol:profile' %}">Your profile</a>
<a href="{{ user.profile.pdf.url }}" class="btn">Your Resume</a>
</div>

   



    

</div>

 
{% endblock %}

mysite/templates/pol/index.html
<!DOCTYPE html>
<html>
  {% load static %}
    <html><link rel="stylesheet" type="text/css" href="{% static 'pol/main.css' %}">
    <link rel="stylesheet" type="text/javascript" href="{% static 'pol/materialize.min.js' %}">
    <meta charset="UTF-8">
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static 'pol/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  


    <style>
        
html {
    background: no-repeat center fixed;
    background-repeat: no-repeat;
    background-size: cover;
    background-color:#e0f7fa;
    background-image: linear-gradient(to bottom ,rgba(145, 238, 241, 0.986),rgb(69, 120, 196));
}
.spinner {
        width: 40px;
        height: 40px;
        background-color: rgb(253, 250, 250);

        position: absolute;
        top: 48%;
        left: 48%;
        -webkit-animation: sk-rotateplane 1.2s infinite ease-in-out;
        animation: sk-rotateplane 1.2s infinite ease-in-out;
      }

      @-webkit-keyframes sk-rotateplane {
        0% { -webkit-transform: perspective(120px) }
        50% { -webkit-transform: perspective(120px) rotateY(180deg) }
        100% { -webkit-transform: perspective(120px) rotateY(180deg)  rotateX(180deg) }
      }

      @keyframes sk-rotateplane {
        0% { 
          transform: perspective(120px) rotateX(0deg) rotateY(0deg);
          -webkit-transform: perspective(120px) rotateX(0deg) rotateY(0deg) 
        } 50% { 
          transform: perspective(120px) rotateX(-180.1deg) rotateY(0deg);
          -webkit-transform: perspective(120px) rotateX(-180.1deg) rotateY(0deg) 
        } 100% { 
          transform: perspective(120px) rotateX(-180deg) rotateY(-179.9deg);
          -webkit-transform: perspective(120px) rotateX(-180deg) rotateY(-179.9deg);
        }
      }
      .spinner-wrapper {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background-color: #7065d4;
      z-index: 999999;

      .preloader-background {
	display: flex;
	align-items: center;
	justify-content: center;
	background-color: #eee;
	
	position: fixed;
	z-index: 100;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;	
}
      }
 

    </style>
<head>
    <title>system</title> 
    <div class="container  ">
          <nav>
    <div class="nav-wrapper  blue">
      <a href="{% url 'pol:mhome' %}" class="brand-logo left">Home</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        {% if user.is_authenticated %}
        <li><a class="btn waves-effect  waves-light blue lighten-2 right" href="{% url 'pol:logout_url' %}">Logout</a>
        </li>
        {% else %}
        <li><a class="btn waves-effect pulse waves-light blue lighten-2 ma2 pa2 right" href="{% url 'pol:login_urls' %}">Login</a>
        </li>
        <li><a class="btn waves-effect pulse waves-light blue lighten-2 right" href="{% url 'pol:register_url' %}">Register</a>
        </li> {% endif %} 
      </ul>
    </div>
  </nav>

    </div>
    <ul id="slide-out" class="sidenav blue">
          
      <li><div class="user-view ">
            
        <div class="background">
             
          </div>
          <div class="right">
  
          </div>
  
        </div>
      </li>
        {% if user.is_authenticated %}
        <li><a class="btn waves-effect  waves-light blue lighten-2 " href="{% url 'pol:resource'  %}"><i class="material-icons right">send</i>Resources</a></li>
        <li><a class="btn waves-effect  waves-light blue lighten-2" href="{% url 'pol:logout_url'  %}"><i class="material-icons right">send</i>logout</a></li>
        <li><a class="btn waves-effect  waves-light blue lighten-2" href="{% url 'pol:dashboard'  %}"><i class="material-icons right">send</i>dashboard</a></li>
  
        {% else %}
       
        <li><a class="btn waves-effect  waves-light blue lighten-2" href="{% url 'pol:login_urls'  %}"><i class="material-icons right">send</i>login</a></li>
            
        {% endif %}    
        <li><div class="divider"></div></li>
    </ul>
    <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
      var elems = document.querySelectorAll('.sidenav');
          
      var instances = M.Sidenav.init(elems); 
      console.log(instances)
      });
</script>
 
    {% block content %}
</head>
<body>
  


    <div class="container center-align">
          <h1>Welcome to Home Page</h1>
 
    <div class="preloader-background">
        <div class="preloader-wrapper big active">
            <div class="spinner-layer spinner-blue-only">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="gap-patch">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="carousel container">
        <a class="carousel-item" href="#one!"><img style="width: 300px; height: 150px;" src=" {{ MEDIA_URL }}pol/ml1.jpg "></a>
        <a class="carousel-item" href="#two!"><img style="width: 300px; height: 150px;" src=" {{ MEDIA_URL }}pol/ml2.png "></a>
        <a class="carousel-item" href="#three!"><img style="width: 300px; height: 150px;" src=" {{ MEDIA_URL }}pol/ml3.png "></a>
        <a class="carousel-item" href="#four!"><img style="width: 300px; height: 150px;" src=" {{ MEDIA_URL }}pol/ml4.jpg "></a>
        <a class="carousel-item" href="#five!"><img style="width: 300px; height: 150px;" src=" {{ MEDIA_URL }}pol/m5.jpg "></a>
      </div>
    <script>
        $(document).ready(function() {
        //Preloader
        preloaderFadeOutTime = 3000;
        function hidePreloader() {
        var preloader = $('.spinner-wrapper');
        preloader.fadeOut(preloaderFadeOutTime);
        }
        hidePreloader();
        });

        document.addEventListener("DOMContentLoaded", function(){
	$('.preloader-background').delay(1700).fadeOut('slow');
	
	$('.preloader-wrapper')
		.delay(1700)
		.fadeOut();
});

        document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.carousel');
    var instances = M.Carousel.init(elems, {
        dist: -50,
        shift: 5,
        duration: 200   ,
    paddding: 5,
    indicators: true,
  });
  });

  // Or with jQuery


        </script>
    {% endblock %}    
</body>
</html>

mysite/templates/pol/profile.html
{% extends 'pol/index.html' %}
{% load static %}

{% block content %}

<div class="container">
 

      <!-- FORM HERE -->
    
    
    <div class="col s12 m8 offset-m2 l6 offset-l3">
        <div class="card-panel  z-depth-1">
          <div class="row valign-wrapper">
            <div class="col s2">
                <img class="circle responsive-img account-img" style="width: 100px; height: 100px;" src="{{ user.profile.image.url }}">
            </div>
            <div class="col s10">
              <span class="">
                <h4>{{ user.username }}</h4>
              </span>
            </div>
          </div>
        </div>
      </div>

<div>
  
</div>
      <div class="">
        <div class="col s12 m6">
          <div class="card ">
            <div class="card-content ">
              <span class="card-title center">Your Profile</span>
              <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}                
               <ul>
                 <l1>{{ u_form.as_p }}</l1>
                 <li>{{ p_form.as_p }} </li>
               </ul> 
                              
            <button class="btn cyan lighten-2" type="submit">Update</button>
        
    </form>  
            </div>
      
          </div>
        </div>
      </div>
    


</div>

{% endblock %}

mysite/templates/pol/resources.html
<html>
   
{% load static %} 

   

    <html><link rel="stylesheet" type="text/css" href="{% static 'pol/style.css' %}">
    <link rel="stylesheet" type="text/javascript" href="{% static 'pol/materialize.min.js' %}">
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static 'pol/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <ul id="slide-out" class="sidenav">
      <li>

      <div class="user-view ">
        <div class="background">
        </div>
        <div class="right">

        </div>
      </div>
      </li>
      
      <li><a class="btn waves-effect  waves-light " href="{% url 'pol:home'  %}"><i class="material-icons right">send</i>Categorizer</a></li>
      <li><div class="divider"></div></li>
  
    </ul>
    <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
          
   <script>
      document.addEventListener('DOMContentLoaded', function() {
       var elems = document.querySelectorAll('.sidenav');
      
       var instances = M.Sidenav.init(elems); 
       console.log(instances)
     });
   


   </script>
    <body>
      <div class="container">
      <ul class="collection with-header grow hoverable blue lighten-3 ">
      <li class="center collection-header blue lighten-3"><h4>Resources</h4></li>
          
    </ul> 
    <div class="collection ">
        <a href="https://www.djangoproject.com/" class=" collection-item ">Django Official Project<i class="material-icons right">send</i></a>
        <a href="https://materializecss.com/" class=" collection-item ">Materialize<i class="material-icons right">send</i></a>        
        <a href="https://getbootstrap.com/" class=" collection-item ">Bootstrap<i class="material-icons right">send</i></a>
        <a href="https://www.w3schools.com/w3css/" class=" collection-item ">W3Schools<i class="material-icons right">send</i></a>
      
    </div>
</body>

  
 </div>
 
    </html>

mysite/templates/pol/upload.html
{% extends 'pol/index.html' %}

{% block content %}
<h1>upload</h1>
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
<input type="file" name="document">
<button type="submit">upload file</button>
</form>
<div>
    {% if url %}
    {{ url }}
    {% endif %}
    <embed src="{{ url }}" type="application/pdf" width="100%" height="600px" >
</div>
{% endblock %}

mysite/templates/pol/upload_book.html
{% extends 'pol/index.html' %}

{% block content %}

<div class="container">

<h1>upload resume</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn">upload your resume here </button>
</form>


<div>
{% endblock %}